### ISSUE TITLE
정보를 불러올 수 없습니다 라고 나옵니다

### ISSUE THREAD

**Issue by franticck** [junheah/MangaViewAndroid#10]
![Screenshot_20210124-234735_MangaView](https://user-images.githubusercontent.com/17270633/105633956-e7b25580-5e9e-11eb-9794-9df3091d44a2.png)
![Screenshot_20210124-234811_MangaView](https://user-images.githubusercontent.com/17270633/105633959-ed0fa000-5e9e-11eb-88a2-205bc4475d6e.png)
![Screenshot_20210124-234820_MangaView](https://user-images.githubusercontent.com/17270633/105633961-f13bbd80-5e9e-11eb-9ca3-6e0e41e1ee32.png)

url 설정도 잘 했는데 정보를 불러올 수 없다고 나오네요
캡챠 업데이트 할때 메인 페이지 까지 잘 뜨는데도 안됩니다
어떤걸 만져야 할까요? 감사합니다

**Comment by junheah** [comment]
url 설정 제대로 해주세요. 최신주소 똑바로 넣어야 됩니다.
