### ISSUE TITLE
만화가 한두 쪽 남겨놓고 넘어가는 현상이 발생합니다..

### ISSUE THREAD

**Issue by YRHowo** [junheah/MangaViewAndroid#11]
좋은 앱 만들어주셔서 항상 잘 쓰고 있다는 감사의 말씀을 먼저 전하고 싶습니다.

제가 지금 쓰고 있는 기종이 삼성 갤럭시 와이드인데, 이전에 사용한 폰에서는 없었던 오류가 계속 발생하고 있습니다.

만화를 보다가 갑자기 몇 장을 남겨놓고 다음 화로 넘어간 다음에 이전 화로 되돌아갈 수 없게 되는 현상인데, 이것이 이번 업데이트로 생긴 오류인지 아니면 제 핸드폰 문제인지 궁금합니다..ㅜ

**Comment by junheah** [comment]
어떤 뷰어를 사용중인가요

**Comment by YRHowo** [comment]
기본 스크롤뷰어를 사용하고 있습니다

**Comment by junheah** [comment]
사진이나 동영상을 첨부해 주실 수 있나요? 정확히 어떻게 되는지를 모르겠어서
