### ISSUE TITLE
갤럭시 폴드에서 노치 무시 기능

### ISSUE THREAD

**Issue by m00nlygreat** [junheah/MangaViewAndroid#12]
안녕하세요. 아래도 인사드렸지만 정말 잘 쓰고 있습니다.

혹시 노치가 있는 디바이스에서 노치를 무시하는 설정의 추가를 고려해주실 수 있을까요?
Perfect View에는 앱 설정에 노치 무시가 있는 걸로 봐서 불가능한 것은 아니라고 생각이 됩니다만 ..

읽어주셔서 감사합니다

**Comment by junheah** [comment]
전체화면 옵션이 필요하다는 말인가요?

**Comment by m00nlygreat** [comment]
> 전체화면 옵션이 필요하다는 말인가요?

맞습니다. 노치를 무시하고 전체화면으로 뷰어 영역을 확장하는 기능입니다

**Comment by junheah** [comment]
추가함 53f5a6e382e602abbd9be3cfc623cf2e5db01c3d
