### ISSUE TITLE
가로화면시 두쪽보기 기능 추가가 가능할까요?

### ISSUE THREAD

**Issue by FuukaHikaru** [junheah/MangaViewAndroid#14]
좋은 어플리케이션 만들어주셔서 감사합니다.
갤럭시 폴드 2를 사용중입니다.
가로 화면시 두 페이지가 나왔으면 좋겠습니다.

설정 중에 페이지 분할 관련 설정이 있어서 앱 자체에서 지원하는 것 같은데
가로 모드를 해도. 설정을 찾아봐도 관련 된 기능이 보이지가 않습니다.

감사합니다.

**Comment by junheah** [comment]
페이지 분할은 가로 사이즈가 세로보다 큰 이미지를 잘라서 두개의 이미지로 보여주는 기능입니다.
두쪽보기는 시간나면 추가해 볼게요.

**Comment by junheah** [comment]
추가함 5509a5bfe853440965c5ef99757fff3ec8c26f6b a6119034eb8dd704e14842b132bb09f30832fcbf 10863576aeddbce39fd89e50478d8c0bfdc42540
