### ISSUE TITLE
탭 길게 안내문 몇번만 나오게 변경해주실 수 있나요.

### ISSUE THREAD

**Issue by proplcy** [junheah/MangaViewAndroid#15]
저는 무한 스크롤이 아니라 탭으로 보고 있는데요. 

이번 업데이트 이후에 회차가 넘어갈때마다 계속 안내문이 길게 뜨닌까 컷이 짧은 작품을 몰아볼때 은근히 불편해요. 

친절하게 안내문 넣어주신건 감사한데 같은 내용이 계속 나오고 없어지기까지 좀 길어서 짧은 작품 몰아볼때 불편하네요 ㅠ 

몇번 문구 나오면 더 이상 안나오게 해주시면 안될까요.

그리고 '첫화보기' 기능이 있으면 좋을거 같습니다. 덕분에 잘 보고 있어요 감사합니다~

**Comment by junheah** [comment]
1982ccebd3261ed30b1568ce7d80db9533960887 : 안내문 표시방식 변경
 - 표시 시간 단축 5초->4초
 - 뷰어 켰을때 처음에만 표시

핫픽스 빌드 : [다운로드](https://github.com/junheah/MangaViewAndroid/raw/master/app/release/mangaViewer_2108011050-release.apk)

**Comment by proplcy** [comment]
> [1982cce](https://github.com/junheah/MangaViewAndroid/commit/1982ccebd3261ed30b1568ce7d80db9533960887) : 안내문 표시방식 변경
> 
> * 표시 시간 단축 5초->4초
> * 뷰어 켰을때 처음에만 표시
> 
> 핫픽스 빌드 : [다운로드](https://github.com/junheah/MangaViewAndroid/raw/master/app/release/mangaViewer_2108011050-release.apk)

핫픽스 빌드 받아서 설치해봤습니다. 느낌인건지 시간은 좀 단축된거 같네요. 

그리고 뷰어 켰을때 처음에만 나올거라 생각했는데 회차 넘어갈때마다 나오네요.

좀 아쉽지만 그래도 대응해주셔서 감사합니다.

**Comment by junheah** [comment]
4b2eb9d72b1d67655b3bfe5387eed40ab9c2b6ac : 첫화보기 메뉴 추가

**Comment by junheah** [comment]
> > [1982cce](https://github.com/junheah/MangaViewAndroid/commit/1982ccebd3261ed30b1568ce7d80db9533960887) : 안내문 표시방식 변경
> > 
> > * 표시 시간 단축 5초->4초
> > * 뷰어 켰을때 처음에만 표시
> > 
> > 핫픽스 빌드 : [다운로드](https://github.com/junheah/MangaViewAndroid/raw/master/app/release/mangaViewer_2108011050-release.apk)
> 
> 핫픽스 빌드 받아서 설치해봤습니다. 느낌인건지 모르겠지만 시간은 좀 단축된거 같네요.
> 
> 그리고 뷰어 켰을때 처음에만 나올거라 생각했는데 회차 넘어갈때마다 나오네요.
> 
> 좀 아쉽지만 그래도 대응해주셔서 감사합니다.

링크를 잘못걸었네요 이거면 될겁니다 : [다운로드](https://github.com/junheah/MangaViewAndroid/raw/dev/app/release/mangaViewer_2108032354-release.apk)

**Comment by proplcy** [comment]
> > > [1982cce](https://github.com/junheah/MangaViewAndroid/commit/1982ccebd3261ed30b1568ce7d80db9533960887) : 안내문 표시방식 변경
> > > 
> > > * 표시 시간 단축 5초->4초
> > > * 뷰어 켰을때 처음에만 표시
> > > 
> > > 핫픽스 빌드 : [다운로드](https://github.com/junheah/MangaViewAndroid/raw/master/app/release/mangaViewer_2108011050-release.apk)
> > 
> > 
> > 핫픽스 빌드 받아서 설치해봤습니다. 느낌인건지 모르겠지만 시간은 좀 단축된거 같네요.
> > 그리고 뷰어 켰을때 처음에만 나올거라 생각했는데 회차 넘어갈때마다 나오네요.
> > 좀 아쉽지만 그래도 대응해주셔서 감사합니다.
> 
> 링크를 잘못걸었네요 이거면 될겁니다 : [다운로드](https://github.com/junheah/MangaViewAndroid/raw/dev/app/release/mangaViewer_2108032354-release.apk)

이거 받으닌까 만화를 클릭시 한번만 표기되고 다음회차에서는 표기가 안되네요. 반영 감사합니다.

저만의 문제라면 죄송합니다. 첫화보기 메뉴를 추가해주셨다고 해서 전편보기를 눌러서 확인해보려고 했는데 

예상치 못한 오류가 발생했습니다 하면서 홈화면으로 돌아와지네요.

**Comment by junheah** [comment]
고쳤고 아예 릴리즈 냈으니 업데이트 하세요

**Comment by proplcy** [comment]
> 고쳤고 아예 릴리즈 냈으니 업데이트 하세요

너무 잘 됩니다. 고쳐주셔서 감사합니다~^^
