### ISSUE TITLE
좋은어플 감사합니다. 혹시 태블릿 가로모드

### ISSUE THREAD

**Issue by shootmg50** [junheah/MangaViewAndroid#20]
태블릿 가로모드 터치뷰어일때 두장보기 고정말고 한장보기도 선택할수 있으면 좋겠습니다.
좋은 어플 만들어 주셔서 감사합니다. 건강하세요~

**Comment by junheah** [comment]
8c1f6797685e93b413aff092f5c72e632b1d8dc5
