### ISSUE TITLE
가로화면시 두쪽보기 시 좌우 페이지 변경

### ISSUE THREAD

**Issue by flamebanana** [junheah/MangaViewAndroid#22]
태블릿 터치뷰어 가로보기 시 두 페이지 보기가 되는데 이때 좌우 페이지 위치를 변경할 수 있으면 좋겠습니다
페이지 분할시 좌우 순서 변경은 터치뷰어 두쪽보기시엔 적용이 안되더군요

**Comment by junheah** [comment]
8c1f6797685e93b413aff092f5c72e632b1d8dc5
