### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by Nhw1010** [junheah/MangaViewAndroid#23]
안드로이드때 잘 사용하던 유저입니다. 혹시 ios버전으로도 따로 제작인 가능할지 궁금해서 남기겟습니다.

**Comment by junheah** [comment]
일단 앱의 성격상 공식 앱스토어에 등록이 불가 합니다.
그렇다면 다른 경로를 통해서 앱을 배포해야 하는데 안드로이드의 경우에는 이게 쉽게 해결 가능합니다.
하지만 ios는 기본적으로 인증되지 않은 앱을 설치하는게 허용되지 않고 편법이 존재하지만 매우 불안정 합니다.
위와 같은 이유로  ios 개발은 고려하고 있지 않습니다.
