### ISSUE TITLE
앱 지원 안드로이드 버전 궁금증에 대하여.

### ISSUE THREAD

**Issue by Tralala-hub** [junheah/MangaViewAndroid#37]
마나모아시절부터 오랜기간 정말 잘 사용하고 있습니다. 감사합니다. 다름이 아니오라, 평소에 만화를 볼 때 사용하던 크레마s Ebook이 있는데 이 제품은 안드로이드10이라 큰 어려움이나 불편함 없이 잘 사용해왔습니다. 그러나 기기가 모종의 이유로 작동이 안되어 예전에 사용하던 Ebook을 꺼내서 만화를 보려 하는데, 웹페이지로 보려니 여러모로 불편함이 느껴지더라구요. 기기의 안드로이드 버전이 2.3.6 진저브레드로 아주 옛날 버전인데. 앱이 이 버전의 기기를 지원하는지 궁금합니다. 그리고 지원을 하지 않는다면, 과거 버전들중 지원하였던 버전이 있는지도 궁금합니다. 항상 감사합니다.

**Comment by junheah** [comment]
외부 라이브러리 종속성으로 인해 안드로이드 4.2버전 부터 지원합니다
