### ISSUE TITLE
ManaToki uses new page encryption method

### ISSUE THREAD

**Issue by DitFranXX** [junheah/MangaViewAndroid#6]
For tip: Same as NewToki uses. This shoud be help: https://github.com/SnakeDoc83/tachiyomi-extensions/blob/8f80effbd508c9040eb4d965f7a13d95990611c8/src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/NewTokiFactory.kt#L52-L64

**Comment by junheah** [comment]
fixed in b7a2a6d36df3e1eef3e2ee104b645ec9e1415571
