### ISSUE TITLE
이미지 가져오기

### ISSUE THREAD

**Issue by bsh123456** [junheah/MangaViewAndroid#63]
1. okhttp3 responese를 통하여 body 추출이 403으로 실패

2. 웹뷰로 접근하여 cloudflare 통과후 onPageFinished에서 body html을 추출 성공

4. 해당 html로 기존에 responese 영역으로 데이터 대입 > 리스트 출력 성공

5. 리스트내 썸네일이 안보임

6. 썸네일 출력이 Glide.with로 이루어짐 해당 url 접근시 cloudflare 발생

7. Glide도 cloudflare 통과 못하는듯... 썸네일이 안보인다면 안에 만화 이미지도 안뜰게 뻔함...

---------------

혹시 okhttps나 Glide에 쿠키값 넣어서 작동 되는건 처리하셨을까요? 웹뷰 onPageFinished 쪽에서 쿠키값들 가져와서 대입해도 403 뜨던데...

**Comment by junheah** [comment]
작업중인 브랜치 푸쉬 가능한가요?
저는 웹뷰에서 turnstile이 통과가 아예 안되더라구요

**Comment by bsh123456** [comment]
> 작업중인 브랜치 푸쉬 가능한가요? 저는 웹뷰에서 turnstile이 통과가 아예 안되더라구요 (#62)
> 
> 챌린지 통과에 성공했으면 쿠키 추출해서 글라이드와 다른 http 요청에 넣어주면 될듯 합니다

제가 깃허브가 익숙지 않아서 어떻게 해드려야될지 모르겠습니다.

설명으로 대체하자면 웹뷰에 user agent 그 브라우저명들 입력하는거 Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.101 Safari/537.36 이런거 입력하는 구간 주석걸면 통과하더라구요

저는 일단 글라이드랑 okhttp쪽에 쿠키 넣어도 잘 안되서... 서치리스트랑 에피소드쪽은 웹뷰에서 html받아와서 body문 교체해주고 만화는 웹뷰로 연결해서 임시로 보고 있습니다. 썸네일이 안보여서 제목으로만 구분해야되지만 그간 저장된 즐겨찾기랑 북마크 이용해서 어디까지 봤는지 파악되니 다행이다 싶습니다ㅠ

**Comment by bsh123456** [comment]
https://github.com/junheah/MangaViewAndroid/assets/168548748/df865216-5b49-472a-9172-82be9114120d
