### ISSUE TITLE
리스트에서 캡차 / 웹툰 썸네일 미표시

### ISSUE THREAD

**Issue by bsh123456** [junheah/MangaViewAndroid#65]
1. 캡차를 통과하기전에 리스트 검색시 > 캡차 들어가도 작동을 안함
해결) MainSearch 쪽에 있는 Utils.showCaptchaPopup(getContext(), 4, fragment, p); 에 url을 포함하도록 수정 / search에서 fetch안에 있는 client.mget 안에 들어가는 url변수를 가져오는 함수 만들어서 사용

![MainSearch](https://github.com/junheah/MangaViewAndroid/assets/168548748/df7740d3-a55a-4bc1-b50f-207a54995606)

![search](https://github.com/junheah/MangaViewAndroid/assets/168548748/7c77b058-4321-4bb6-b2a8-7b79bf26d474)

2. 웹툰의 경우 리스트 썸네일 + 에피소드 썸네일 미표시
해결) 웹툰의 경우 썸네일 도메인이 2개임 https://img1.newtoki20.org 와 https://manatoki336.net 이중에 replaceAll을 이용하여 img1 형태로 변경해준뒤 만들어놓으신 getGlideUrl형태로 변환한뒤 Glide에 넣어야지만 썸네일이 제대로 나옴, 에피소드쪽도 마찬가지로 수정, 최근에 본 만화메뉴에서 썸네일 주소가 이전숫자주소로 저장되어있는것 고려해야 안터짐 주의, img1.newtoki20.org 주소가 바뀌면 어떻게 해야하나 의문임 고정일까?

![thumb](https://github.com/junheah/MangaViewAndroid/assets/168548748/c4d3fe17-9882-4c28-9bba-6df03cccaba9)

------------------------

일단 응급조치겸해서 사용하고 있고, 참고해주세요

**Comment by junheah** [comment]
[pr](https://wayhome25.github.io/git/2017/07/08/git-first-pull-request-story/)을 작성해주세요

**Comment by bsh123456** [comment]
@junheah 옙, 덕분에 쾌적하게 사용하고 있습니다~

**Comment by junheah** [comment]
pr 머지 완료 후에 닫아주세요~

**Comment by bsh123456** [comment]
@junheah 저소스 따로 다운받아서 제가 기능 추가해서 쓰는거라 머지가 안될듯 싶어여, 일단 이슈는 닫겠습니다
