### ISSUE TITLE
정보를 불러오는데 실패했습니다

### ISSUE THREAD

**Issue by green1052** [junheah/MangaViewAndroid#7]
![Screenshot_20201019-183004_MangaView](https://user-images.githubusercontent.com/34261355/96427254-47161f00-1239-11eb-8b3a-dd0c9a3afbd3.jpg)
![Screenshot_20201019-183007_MangaView](https://user-images.githubusercontent.com/34261355/96427263-4a110f80-1239-11eb-85dd-93bbb4cabf32.jpg)

라고 뜨는데 어떻게 해결하나요?

**Comment by junheah** [comment]
기본적으로 마나토끼 기반이라 주소를 그쪽으로 설정해줘야 돼요
