### ISSUE TITLE
설정에서 URL자동설정시 메인페이지 업데이트 안되는 증상

### ISSUE THREAD

**Issue by NID277** [junheah/MangaViewAndroid#8]
안녕하세요.

현재 v.2012061935 버전 사용중이며

설정에서 URL 자동설정시 메인페이지 업데이트가 안되고있으며 

URL 자동설정을 해제하면 정상적으로 메인페이지 업데이트가 

진행되는 증상에 대해서 리포트 및 업데이트 요청 드리고자 

이슈에 글을 남기게 되었습니다.

잘 부탁드립니다.

**Comment by junheah** [comment]
고침 7a1ed251a69caa8228fa74f225ad8e5e2546e324

**Comment by NID277** [comment]
대단히 감사합니다.
